version: "3"
services:
  semillero-db:
    image: mariadb:10.3
    volumes:
      # para que al levantar la DB use el .sql que crea la database y el user, ver https://hub.docker.com/_/mariadb/
      - ./src/main/resources/sql-migrations/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TERM=xterm
    ports:
      - "3307:3306"

  semillero-api:
    image: maven:3.5.2
    working_dir: /semillero2-api
    volumes:
      - $PWD:/semillero2-api
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    depends_on:
      - semillero-db
