### create company
POST {{host}}/company
Content-Type: application/json

{
    "name": "Pivotal",
    "email": "Josh"
}

### list companies
GET {{host}}/company

### get company by id
GET {{host}}/company/1

###
