###
OPTIONS {{host}}/company
Access-Control-Request-Method: GET
Origin: localhost

### create company
POST {{host}}/company
Authorization: Basic {{auth}}
Content-Type: application/json

{
    "name": "Pivotal",
    "contact": "Josh",
    "email": "josh@pivotal.com",
    "comments": "my comments on Josh"
}

### create company
PUT {{host}}/company/1
Authorization: Basic {{auth}}
Content-Type: application/json

{
    "name": "new Pivotal",
    "contact": "new Josh",
    "email": "josh@pivotal.com"
}

### list companies
GET {{host}}/company?name=IVOT&workers=false&interviews=true&page=0&size=10
Authorization: Basic {{auth}}

### get company by id
GET {{host}}/company/1
Authorization: Basic {{auth}}

###
