### create interview
POST {{host}}/interview
Authorization: Basic {{auth}}
Content-Type: application/json

{
    "student": 3,
    "company": 1
}

### list interviews
GET {{host}}/interview
Authorization: Basic {{auth}}

### get interview by id
GET {{host}}/interview/1
Authorization: Basic {{auth}}

###
