### create interview
POST {{host}}/interview
Content-Type: application/json

{
    "student": 3,
    "company": 1
}

### list interviews
GET {{host}}/interview

### get interview by id
GET {{host}}/interview/1

###
