### create node
POST {{host}}/node
Authorization: Basic {{auth}}
Content-Type: application/json

{
    "name": "Capital",
    "address": "domicilio del nodo"
}

### list nodes
GET {{host}}/node
Authorization: Basic {{auth}}

### get node by id
GET {{host}}/node/1
Authorization: Basic {{auth}}

###
