### create node
POST {{host}}/node
Content-Type: application/json

{
    "name": "Capital",
    "address": "domicilio del nodo"
}

### list nodes
GET {{host}}/node

### get node by id
GET {{host}}/node/1

###
