### list graduated
GET {{host}}/student

### get graduated by id
GET {{host}}/student/3

### get graduated by id
DELETE {{host}}/student/3

###
POST {{host}}/student
Content-Type: application/json

{
    "name": "El Graduado",
    "node": 2
}

###
