### list student
GET {{host}}/student

### get student by id
GET {{host}}/student/3

### delete student by id
DELETE {{host}}/student/3

###
POST {{host}}/student
Content-Type: application/json

{
    "name": "El Estudiante",
    "node": 2
}

###
POST {{host}}/student/bulk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="csv"; filename="egresados.csv"

nombre,apellido,mail,celular,egresado,nodo,fecha
Silvia,Merlano,Silvia.merlano@gmail.com,,,Capital,2017-2
Jose,Morales,Joseamorales2@gmail.com,,Si,Capital,2017-2
fernando,schmer,fers@sion.com,59443911,,Capital,2017-2
--boundary

###
